# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal webpage
email: 1488maiklm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal webpage (blog) where I publish my completed and recent projects/ideas
  Also you may read my CV here as well by navigating to CV page.
baseurl: "/assets" # the subpath of your site, e.g. /blog
url: "http://mikhailms.github.io"
github_username:  mikhailms

# Build settings
markdown: kramdown
